baseurl = "https://anionline.me/"
title = "Ani's blog"
theme = "creative"
languageCode = "en-us"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Ani's blog"
  sidebarAbout = [ "Nemo homimem est qui mundum non reddat meliorem" ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "posts/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  stackoverflow = "full profile url in stackoverflow"
  github        = "full profile url in github"